name: build python

on: push

jobs:
  build-library:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -qqy wget curl lsb-release software-properties-common gnupg build-essential libc6-dev libtinfo5 libxkbcommon-dev m4 zip git cmake ninja-build
          wget -P /tmp -q http://ftp.gnu.org/gnu/autoconf/autoconf-2.71.tar.gz
          tar zxf /tmp/autoconf-2.71.tar.gz -C /tmp
          (cd /tmp/autoconf-2.71 && sudo ./configure && sudo make && sudo make install)
          wget -P /tmp -q http://ftp.gnu.org/gnu/automake/automake-1.16.tar.gz
          tar zxf /tmp/automake-1.16.tar.gz -C /tmp
          (cd /tmp/automake-1.16 && sudo ./configure && sudo make && sudo make install)
          ./run.sh get_deps
          ./run.sh build
      - name: Package
        run: |
          rm -rf out/wasi-python/lib/python3.10/config-3.10
          (cd out/wasi-python/lib && zip -r python.zip python3.10)
          mkdir dist
          mv out/wasi-python/bin/python3.10.wasm ./dist
          mv out/wasi-python/lib/python3.10/ ./dist
      - name: Publish
        uses: actions/upload-artifact@v3
        with:
          name: python
          path: dist
