name: publish

on:
  push:
    tags:
      - "v*"

jobs:
  build-python:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -qqy lsb-release software-properties-common gnupg build-essential libc6-dev libtinfo5 libxkbcommon-dev m4 git cmake ninja-build automake autoconf
          ./run.sh get_deps
          ./run.sh build
      - name: Package
        run: |
          rm -rf out/wasi-python/lib/python/config-*
          (cd out/wasi-python/lib/ && tar -czf python.tar.gz $(readlink python))
          mkdir -p dist
          cp -Lr out/wasi-python/lib/python.tar.gz ./dist
          cp -L out/wasi-python/bin/python3.wasm ./dist
      - name: Publish
        uses: "marvinpinto/action-automatic-releases@919008cf3f741b179569b7a6fb4d8860689ab7f0"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            dist/*
